import { NextResponse } from 'next/server'
import { getCurrentUser } from '@/lib/auth-helpers'

export async function GET() {
  const { supabase, tenantId } = await getCurrentUser()
  if (!tenantId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: deals, error } = await supabase
    .from('deals')
    .select(`
      *,
      customer:counterparties!deals_customer_id_fkey(id, name),
      supplier:counterparties!deals_supplier_id_fkey(id, name),
      product:products(id, name, hs_code)
    `)
    .eq('tenant_id', tenantId)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(deals)
}

export async function POST(request) {
  const { supabase, tenantId, profile } = await getCurrentUser()
  if (!tenantId) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await request.json()

  // Handle inline counterparty creation
  let customerId = body.customer_id
  let supplierId = body.supplier_id

  if (body.customer_name && !customerId) {
    const { data: cust } = await supabase
      .from('counterparties')
      .insert({ tenant_id: tenantId, name: body.customer_name, type: 'customer' })
      .select('id')
      .single()
    customerId = cust?.id
  }

  if (body.supplier_name && !supplierId) {
    const { data: supp } = await supabase
      .from('counterparties')
      .insert({ tenant_id: tenantId, name: body.supplier_name, type: 'supplier' })
      .select('id')
      .single()
    supplierId = supp?.id
  }

  const { data: deal, error } = await supabase
    .from('deals')
    .insert({
      tenant_id: tenantId,
      deal_number: '', // Auto-generated by trigger
      status: 'draft',
      trade_type: body.trade_type || 'cross_border_direct',
      transport_mode: body.transport_mode || 'ocean',
      user_role: body.user_role || 'trader',
      customer_id: customerId,
      supplier_id: supplierId,
      buy_incoterm: body.buy_incoterm,
      buy_location: body.buy_location,
      sell_incoterm: body.sell_incoterm,
      sell_location: body.sell_location,
      unit_price: body.unit_price,
      quantity: body.quantity || 1,
      quantity_unit: body.quantity_unit || 'containers',
      cost_currency: body.cost_currency || 'USD',
      sales_currency: body.sales_currency || 'USD',
      supplier_payment_terms: body.supplier_payment_terms,
      customer_payment_terms: body.customer_payment_terms,
      hs_code: body.hs_code,
      created_by: profile.id,
    })
    .select(`
      *,
      customer:counterparties!deals_customer_id_fkey(id, name),
      supplier:counterparties!deals_supplier_id_fkey(id, name)
    `)
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(deal, { status: 201 })
}
